modLoader="javafml"
loaderVersion="[33,)"
license="The Unlicense"

[[mods]]
    modId="wailaharvestability"
    version="${file.jarVersion}"
    displayName="Waila Harvestability"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/waila-harvestability"
    issueTrackerURL="https://github.com/squeek502/WailaHarvestability/issues"
    authors="squeek"
    credits=""
    description='''
    An add-on for Waila that adds information about the harvestability of what you are looking at
    '''

[[dependencies.wailaharvestability]]
    modId="waila"
    mandatory=true
    versionRange="[1.10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wailaharvestability]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wailaharvestability]]
    modId="tconstruct"
    mandatory=false
    ordering="AFTER"
    side="BOTH"